version: "3.9"
services:
  nats:
    image: nats
    #    networks:
    #      - openfmb
  replay:
    image: oesinc/openfmb.adapters:a008ef9
    depends_on:
      - nats
        #    networks:
        #      - openfmb
  hmi:
    image: oesinc/openfmb.hmi:latest
    depends_on:
      - nats
        #    networks:
        #      - openfmb

