version: "3.9"
services:
  nats:
    image: nats
  replay:
    image: oesinc/openfmb.adapters:a008ef9
    depends_on:
      - nats
    volumes:
      - ./replay:/cfg
    command: -c /cfg/adapter.yaml
  hmi:
    image: oesinc/openfmb.hmi:latest
    depends_on:
      - nats
    volumes:
      - ./hmi:/cfg
    environment:
      APP_CONF: /cfg/config/app.toml
      APP_DIR_NAME: /cfg
    ports: [32771]
